"""Query finite structured logs through immutable IXR query plans.

Import tooling names here, independently of the core logging package.
Python execution is the default; Polars execution is optional.
"""

from slogger.tools.core.bindings import FieldBinding, GroupBinding
from slogger.tools.core.builders import Field, all_of, any_of, logger_prefix, not_
from slogger.tools.core.filter_language import (
    FilterChoice,
    FilterCompletion,
    FilterSyntaxError,
    complete_filter,
    format_field_path,
    parse_field_path,
    parse_filter,
)
from slogger.tools.core.ixr import (
    And,
    ArrayContains,
    Compare,
    Exists,
    Expression,
    FieldRef,
    In,
    Literal,
    Not,
    Or,
    StringMatch,
)
from slogger.tools.core.plan import (
    AggregateSpec,
    GroupedPlan,
    PlanResult,
    QueryPlan,
    count_rows,
    max_of,
    mean_of,
    min_of,
    scan,
    sum_of,
)
from slogger.tools.errors import ToolError
from slogger.tools.investigation import (
    AggregateJob,
    AggregatePage,
    AggregateResult,
    AggregateScope,
    CacheClearResult,
    CacheStore,
    CaptureStatus,
    Diagnostic,
    FilterJob,
    FilterScope,
    Investigation,
    ManagedStorage,
    OperationStatus,
    RecordIdentity,
    RecordPage,
    RecordView,
    ResourceLimits,
    ResourceUsage,
    SourceBoundary,
    TraceTree,
    TreeJob,
    TreePage,
    TreeRow,
    TreeScope,
    TreeStatus,
    ViewScope,
    default_cache_dir,
)
from slogger.tools.investigation.search import (
    SearchJob,
    SearchOptions,
    SearchProjection,
    SearchResult,
    SearchScope,
)

__all__ = [
    "DiscoveryChoice",
    "DiscoveryCompletionPage",
    "DiscoveryIndex",
    "DiscoveryJob",
    "DiscoveryPage",
    "DiscoveryScope",
    "DiscoveryStatus",

    "SearchJob",
    "SearchOptions",
    "SearchProjection",
    "SearchResult",
    "SearchScope",
    "FieldBinding",
    "GroupBinding",
    "AggregateJob",
    "AggregatePage",
    "AggregateResult",
    "AggregateScope",
    "FilterChoice",
    "FilterCompletion",
    "complete_filter",
    "FilterSyntaxError",
    "format_field_path",
    "parse_field_path",
    "parse_filter",
    "FilterJob",
    "FilterScope",
    "OperationStatus",
    "RecordView",
    "ViewScope",
    "CaptureStatus",
    "CacheClearResult",
    "CacheStore",
    "default_cache_dir",
    "Diagnostic",
    "Investigation",
    "ManagedStorage",
    "RecordIdentity",
    "RecordPage",
    "ResourceLimits",
    "ResourceUsage",
    "SourceBoundary",
    "TraceTree",
    "TreeJob",
    "TreePage",
    "TreeRow",
    "TreeScope",
    "TreeStatus",
    "Expression",
    "FieldRef",
    "Literal",
    "Compare",
    "In",
    "Exists",
    "StringMatch",
    "ArrayContains",
    "And",
    "Or",
    "Not",
    "AggregateSpec",
    "Field",
    "GroupedPlan",
    "PlanResult",
    "QueryPlan",
    "ToolError",
    "SourceOrigin",
    "all_of",
    "any_of",
    "count_rows",
    "logger_prefix",
    "max_of",
    "mean_of",
    "min_of",
    "not_",
    "scan",
    "sum_of",
]

from .core.runtime import SourceOrigin
from .investigation.discovery import (
    DiscoveryChoice,
    DiscoveryCompletionPage,
    DiscoveryIndex,
    DiscoveryJob,
    DiscoveryPage,
    DiscoveryScope,
    DiscoveryStatus,
)
